#  conda env create --name ChIPseq_mapping --file environment.yaml 
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - snakemake=7.25.2
  - pandas=2.0.1
  - cutadapt=4.4
  - fastqc=0.12.1
  - bowtie2=2.5.1
  - picard=3.0.0
  - samtools=1.17
  - conda-forge::ncurses=6.3
  - snakemake-wrapper-utils=0.5.3
  - r-tidyverse=2.0.0
  - liftoff
  - bioconductor-genomicranges
  - bioconductor-rtracklayer
